### ISSUE TITLE
Problems with install.sh

### ISSUE THREAD

**Issue by facchinm** [arduino/arduino-connector#11]
- uninstall is broken, it doesn't check for service/file existence and thus it crashes badly

- when I give my credentials, I get
```2017/07/07 13:47:13 requestCert - POST /: expected 200 OK, got 404 Not Found```

@matteosuppo

**Comment by mastrolinux** [comment]
Now it blocks at:

```
+ sudo -E ./arduino-connector -register -install
Insert your arduino username
myusername
Insert your arduino password
2017/12/05 13:56:50 AskCredentials - authenticate: status = 301 Moved Permanently, response = 
```
