### ISSUE TITLE
Missing description and size for packages

### ISSUE THREAD

**Issue by smellai** [arduino/arduino-connector#26]
![image](https://user-images.githubusercontent.com/1763268/34490963-e6dc9ad2-efe1-11e7-9eb3-5386a640f7aa.png)

It's possible to return this data @cmaglie ?

**Comment by cmaglie** [comment]
yes, I'm looking at this in a moment

**Comment by cmaglie** [comment]
Fixed in https://github.com/arduino/go-apt-client/commit/799c99bfb9eaca8fa16844f1c9a1232edac97382
