### ISSUE TITLE
Missing packages API

### ISSUE THREAD

**Issue by AlbyIanna** [arduino/arduino-connector#29]
The following calls are not available:
- install
- update
- upgrade
- remove

**Comment by AlbyIanna** [comment]
Actually they already exist. My bad, I  was looking at the TODO section in the readme.

**Comment by cmaglie** [comment]
Now that I've added the documentation I see that there is a possible issue here:

https://github.com/arduino/arduino-connector/blob/c69c6f370c8c1e22071ea6994f59704d2d0613df/status.go#L152

if `err` is `nil` the `err.Error()` call will panic.

@AlbyIanna I'm going to slightly change the output from:

```
	type response struct {
		Result string
		Output string
	}
```

to

```
	type response struct {
		Error string `json:"error"`
		Output string `json:"output"`
	}
```

and set Error to the string "nil" if `err` is `nil`.

**Comment by cmaglie** [comment]
-> https://github.com/arduino/arduino-connector/commit/d87603fdd299d7c0bbf26353eb67cd082e5a8ca2
