### ISSUE TITLE
Missing repositories API 

### ISSUE THREAD

**Issue by AlbyIanna** [arduino/arduino-connector#30]
The following calls are not available:
- list
- add
- remove
- edit

**Comment by cmaglie** [comment]
This api already exists, the docs are incomplete:

https://github.com/arduino/arduino-connector/blob/72721f65a48d1f892f8d3672c60bc2240544444b/main.go#L242-L245
https://github.com/arduino/arduino-connector/blob/master/handler_apt_repositories.go

I'm going to add the missing docs.

**Comment by AlbyIanna** [comment]
Sorry, my bad. I was looking at the TODO section in the readme.
